### ISSUE TITLE
match max lenth for issues

### ISSUE THREAD

**Issue by archonwang** [stgeneral/redmine-progressive-gantt-mods#10]
@stgeneral , 
open gantt with project with sub-project, occur 500 error, please check it.
Thanks

error log
```

Started GET "/projects/uth_rdc/issues/gantt" for 192.168.20.231 at 2017-03-28 14:02:44 +0800
Processing by GanttsController#show as */*
  Parameters: {"project_id"=>"uth_rdc"}
  Current user: hui.wang (id=8)
Read fragment views/queries/filter/user-8/2017-03-18T08:45:08Z/2017-03-23 02:44:18 UTC/e42c5980be4ccd0f7205b2df55f850cf (0.3ms)
  Rendered plugins/redmine_performance/app/views/queries/_filters.html.erb (17.2ms)
STATEMENT projects.lft >= 4 AND projects.rgt <= 35 AND (issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=0))
  Rendered plugins/progressive_gantt_mods/app/views/gantts/show.html.erb (1720.8ms)
Completed 500 Internal Server Error in 1832ms (ActiveRecord: 482.2ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_request.text.erb (0.4ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_session.text.erb (1.8ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_environment.text.erb (3.5ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.7ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.2ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.7ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (18.0ms)

ActionView::Template::Error (uninitialized constant Progressive::GanttPatch::MaxLinesLimitReached):
    125: 
    126:   # Width of the entire chart
    127:   g_width = ((@gantt.date_to - @gantt.date_from + 1) * zoom).to_i
    128:   @gantt.render(:top => headers_height + 8,
    129:                 :zoom => zoom,
    130:                 :g_width => g_width,
    131:                 :subject_width => subject_width,
  plugins/progressive_gantt_mods/lib/progressive/gantt_patch.rb:17:in `render_object_row_with_assignees'
  lib/redmine/helpers/gantt.rb:246:in `block in render_issues'
  lib/redmine/helpers/gantt.rb:241:in `each'
  lib/redmine/helpers/gantt.rb:241:in `render_issues'
  lib/redmine/helpers/gantt.rb:220:in `block in render_project'
  lib/redmine/helpers/gantt.rb:276:in `increment_indent'
  lib/redmine/helpers/gantt.rb:217:in `render_project'
  lib/redmine/helpers/gantt.rb:205:in `block in render'
  app/models/project.rb:817:in `block in project_tree'
  app/models/project.rb:813:in `each'
  app/models/project.rb:813:in `project_tree'
  lib/redmine/helpers/gantt.rb:203:in `render'
  plugins/progressive_gantt_mods/app/views/gantts/show.html.erb:128:in `_915c27db285f596f6173d15d69c496c5'
  app/controllers/gantts_controller.rb:43:in `block (2 levels) in show'
  app/controllers/gantts_controller.rb:42:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by stgeneral** [comment]
Thanks for the report, but I'm not sure when I have time to check this. We don't use this plugin now.

**Comment by archonwang** [comment]
@mi-yo , Could you please fix it?
 Thanks
