### ISSUE TITLE
not working with redmine 3.1.0 

### ISSUE THREAD

**Issue by yaroslav-osipov** [stgeneral/redmine-progressive-gantt-mods#4]
After update Redmine from 2.6.3 to 3.1.0 Gantt chart don't work.
Error: wrong number of arguments (3 for 5)
Log: 
D:/Bitnami/Redmine/apps/redmine/htdocs/lib/redmine/helpers/gantt.rb:723:in `html_task'
D:/Bitnami/Redmine/apps/redmine/htdocs/plugins/progressive_gantt_mods/lib/progressive/gantt_patch.rb:29:in `line_for_issue_with_subject'
D:/Bitnami/Redmine/apps/redmine/htdocs/plugins/progressive_gantt_mods/lib/progressive/gantt_patch.rb:14:in `block in render_issues_with_assignees'
D:/Bitnami/Redmine/apps/redmine/htdocs/plugins/progressive_gantt_mods/lib/progressive/gantt_patch.rb:11:in `each'
D:/Bitnami/Redmine/apps/redmine/htdocs/plugins/progressive_gantt_mods/lib/progressive/gantt_patch.rb:11:in `render_issues_with_assignees'
D:/Bitnami/Redmine/apps/redmine/htdocs/lib/redmine/helpers/gantt.rb:220:in `block in render_project'
D:/Bitnami/Redmine/apps/redmine/htdocs/lib/redmine/helpers/gantt.rb:276:in `increment_indent'
D:/Bitnami/Redmine/apps/redmine/htdocs/lib/redmine/helpers/gantt.rb:217:in `render_project'
D:/Bitnami/Redmine/apps/redmine/htdocs/lib/redmine/helpers/gantt.rb:205:in `block in render'
D:/Bitnami/Redmine/apps/redmine/htdocs/app/models/project.rb:768:in `block in project_tree'
D:/Bitnami/Redmine/apps/redmine/htdocs/app/models/project.rb:764:in `each'
D:/Bitnami/Redmine/apps/redmine/htdocs/app/models/project.rb:764:in `project_tree'
D:/Bitnami/Redmine/apps/redmine/htdocs/lib/redmine/helpers/gantt.rb:203:in `render'
D:/Bitnami/Redmine/apps/redmine/htdocs/plugins/progressive_gantt_mods/app/views/gantts/show.html.erb:123:in `_plugins_progressive_gantt_mods_app_views_gantts_show_html_erb___284887737_62604996'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionview-4.2.3/lib/action_view/template.rb:145:in `block in render'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:166:in `instrument'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionview-4.2.3/lib/action_view/template.rb:333:in `instrument'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionview-4.2.3/lib/action_view/template.rb:143:in `render'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:14:in `render'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb:42:in `render_template'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb:23:in `render'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:100:in `_render_template'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal/streaming.rb:217:in `_render_template'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:83:in `render_to_body'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/abstract_controller/rendering.rb:25:in `render'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:16:in `render'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
D:/Bitnami/Redmine/ruby/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/core_ext/benchmark.rb:12:in `ms'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:43:in `render'
D:/Bitnami/Redmine/apps/redmine/htdocs/app/controllers/gantts_controller.rb:43:in `block (2 levels) in show'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal/mime_responds.rb:215:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal/mime_responds.rb:215:in `respond_to'
D:/Bitnami/Redmine/apps/redmine/htdocs/app/controllers/gantts_controller.rb:42:in `show'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:198:in `process_action'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:496:in `block (2 levels) in around'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:311:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:311:in `block (2 levels) in halting'
D:/Bitnami/Redmine/apps/redmine/htdocs/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:430:in `block in make_lambda'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:310:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:310:in `block in halting'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:495:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:495:in `block in around'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:137:in `process'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:30:in `process'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:196:in `dispatch'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:237:in `block in action'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:45:in `serve'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/flash.rb:260:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/cookies.rb:560:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/active_record/query_cache.rb:36:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:84:in `run_callbacks'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:38:in `call_app'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `block in call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:26:in `tagged'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `tagged'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/static.rb:116:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.3/lib/rails/application.rb:165:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `public_send'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `method_missing'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/connection.rb:82:in `block in pre_process'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/connection.rb:80:in `catch'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/connection.rb:80:in `pre_process'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/connection.rb:55:in `process'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/connection.rb:41:in `receive_data'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3-x86-mingw32/lib/eventmachine.rb:187:in `run_machine'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3-x86-mingw32/lib/eventmachine.rb:187:in `run'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/backends/base.rb:73:in `start'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/server.rb:162:in `start'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/controllers/controller.rb:87:in `start'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/runner.rb:200:in `run_command'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/thin-1.6.1-x86-mingw32/lib/thin/runner.rb:156:in `run!'
D:/Bitnami/Redmine/ruby/lib/ruby/gems/2.0.0/gems/thin-1.6.1-x86-mingw32/bin/thin:6:in `<top (required)>'
D:/Bitnami/Redmine/apps/redmine/htdocs/bin/thin:16:in `load'
D:/Bitnami/Redmine/apps/redmine/htdocs/bin/thin:16:in `<main>'

**Comment by stgeneral** [comment]
@yaroslav-osipov thanks for the report. I'm not sure if I will maintain this plugin and add compatibility with the newer versions of Redmine. Feel free to make and fork and contribute the fix.
